import turtle
bob=turtle.Turtle()
a=""
b=0
def fly(event):
    global a
    if event.x >45  and event.x < 104:
        if event.y >274 and event.y <322:
            a += "1"
    if event.x >104  and event.x < 164:
        if event.y >274 and event.y <322:
            a += "2"
    if event.x >164  and event.x < 224:
        if event.y >274 and event.y <322:
            a += "3"
    if event.x >45 and event.x <104:
        if event.y >224 and event.y <273:
            a += "4"
    if event.x >104 and event.x <164:
        if event.y >224 and event.y <273:
            a += "5"
    if event.x >164 and event.x <224:
        if event.y >224 and event.y <273:
            a += "6"
    if event.x >45 and event.x <104:
        if event.y >174 and event.y <223:
            a += "7"
    if event.x >104 and event.x <164:
        if event.y >174 and event.y <223:
            a += "8"
    if event.x >164 and event.x <224:
        if event.y >174 and event.y <223:
            a += "9"
    if event.x >45 and event.x <104:
        if event.y >124 and event.y <173:
            a = " "
            turtle.up()
            turtle.setpos(-310, 260)
            turtle.down()
            turtle.color("Dim Gray", "Dim Gray")
            turtle.begin_fill()
            turtle.fd(180)
            turtle.right(90)
            turtle.fd(40)
            turtle.right(90)
            turtle.fd(180)
            turtle.right(90)
            turtle.fd(40)
            turtle.end_fill()
            turtle.right(90)
            turtle.up()
            turtle.setpos(-300, 220)
            turtle.down()
            turtle.color("White", "Gray")
    if event.x >224 and event.x <284:
        if event.y >224 and event.y <273:
            a += "-"
    if event.x >224 and event.x <284:
        if event.y >174 and event.y <223:
            a += "*"
    if event.x >164 and event.x <224:
        if event.y >124 and event.y <173:
            a += "%"
    if event.x >224 and event.x <284:
        if event.y >274 and event.y <322:
            a += "+"
    if event.x >164 and event.x <224:
        if event.y >324 and event.y <373:
            a += "."
    if event.x >45 and event.x <164:
        if event.y >324 and event.y <373:
            a += "0"
    if event.x >224 and event.x <284:
        if event.y >124 and event.y <173:
            a += "/"
    if event.x >224 and event.x <284:
        if event.y >324 and event.y <373:
            if "%" not in a:
                result = eval(a)
            else:
                a = a.split("%")
                f = int(a[0])
                s = int(a[1])
                per=int((f/s)*100)
                result = "%d"%per
            a = " "
            turtle.up()
            turtle.setpos(-300, 260)
            turtle.down()
            turtle.color("Dim Gray", "Dim Gray")
            turtle.begin_fill()
            turtle.fd(180)
            turtle.right(90)
            turtle.fd(40)
            turtle.right(90)
            turtle.fd(180)
            turtle.right(90)
            turtle.fd(40)
            turtle.end_fill()
            turtle.right(90)
            turtle.up()
            turtle.setpos(-300, 220)
            turtle.down()
            turtle.color("White", "Gray")
            turtle.write(result, font = ("AppleGothic", 30))
    if event.x >104 and event.x <164:
        if event.y >124 and event.y <173:
            b = int(a)*(-1)
            a = ""
            turtle.up()
            turtle.setpos(-300, 260)
            turtle.down()
            turtle.color("Dim Gray", "Dim Gray")
            turtle.begin_fill()
            turtle.fd(180)
            turtle.right(90)
            turtle.fd(40)
            turtle.right(90)
            turtle.fd(180)
            turtle.right(90)
            turtle.fd(40)
            turtle.end_fill()
            turtle.right(90)
            turtle.up()
            turtle.setpos(-300, 220)
            turtle.down()
            turtle.color("White", "Gray")
            a = str(b)
    if event.x >60  and event.x < 70:
        if event.y >55 and event.y <66:
            turtle.clear()
turtle.ht()
turtle.speed(100)
turtle.up()
turtle.setpos(-300, 300)
turtle.down()
turtle.color("Dim Gray", "Dim Gray")
turtle.begin_fill()
turtle.fd(200)
for i in range(30):
    turtle.right(3)
    turtle.fd(1)
turtle.fd(292)
for i in range(30):
    turtle.right(3)
    turtle.fd(1)
turtle.fd(200)
for i in range(30):
    turtle.right(3)
    turtle.fd(1)
turtle.fd(292)
for i in range(30):
    turtle.right(3)
    turtle.fd(1)
turtle.end_fill()
turtle.up()
turtle.setpos(-299, 275)
turtle.down()
turtle.color("Dim Gray", "Orange Red")
turtle.begin_fill()
turtle.circle(7)
turtle.end_fill()
turtle.up()
turtle.setpos(-280, 275)
turtle.down()
turtle.color("Dim Gray", "Orange")
turtle.begin_fill()
turtle.circle(7)
turtle.end_fill()
turtle.up()
turtle.setpos(-261, 275)
turtle.down()
turtle.color("Dim Gray", "Lime Green")
turtle.begin_fill()
turtle.circle(7)
turtle.end_fill()
turtle.up()
turtle.setpos(-319.59, 220)
turtle.down()
def but():
    turtle.color("Dim Gray", "Gray")
    turtle.begin_fill()
    turtle.fd(60)
    turtle.right(90)
    turtle.fd(50)
    turtle.right(90)
    turtle.fd(60)
    turtle.right(90)
    turtle.fd(50)
    turtle.end_fill()
but()
turtle.up()
turtle.back(50)
turtle.right(90)
turtle.fd(20)
turtle.color("Black", "Dim Gray")
turtle.write("C", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-259.59, 220)
turtle.down()
but()
turtle.up()
turtle.back(43)
turtle.right(90)
turtle.fd(12)
turtle.down()
turtle.color("Black", "Dim Gray")
turtle.write("+/-", font=("AppleGothic", 25))
turtle.up()
turtle.setpos(-199.59, 220)
turtle.down()
but()
turtle.up()
turtle.back(45)
turtle.right(90)
turtle.fd(18)
turtle.down()
turtle.color("Black", "Dim Gray")
turtle.write("%", font=("AppleGothic", 25))
turtle.up()
turtle.setpos(-139.59, 220)
turtle.down()
turtle.color("Dim Gray", "Dark Orange")
turtle.begin_fill()
turtle.fd(59)
turtle.right(90)
turtle.fd(50)
turtle.right(90)
turtle.fd(59)
turtle.right(90)
turtle.fd(50)
turtle.end_fill()
turtle.back(50)
turtle.right(90)
turtle.fd(25)
turtle.color("White", "Dark Orange")
turtle.write("/", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-319.59, 170)
turtle.down()
but()
turtle.back(50)
turtle.right(90)
turtle.fd(20)
turtle.color("Black", "Dim Gray")
turtle.write("7", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-259.59, 170)
turtle.down()
but()
turtle.back(50)
turtle.right(90)
turtle.fd(20)
turtle.color("Black", "Dim Gray")
turtle.write("8", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-199.59, 170)
turtle.down()
but()
turtle.back(50)
turtle.right(90)
turtle.fd(20)
turtle.color("Black", "Dim Gray")
turtle.write("9", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-139.59, 170)
turtle.down()
turtle.color("Dim Gray", "Dark Orange")
turtle.begin_fill()
turtle.fd(59)
turtle.right(90)
turtle.fd(50)
turtle.right(90)
turtle.fd(59)
turtle.right(90)
turtle.fd(50)
turtle.end_fill()
turtle.up()
turtle.back(45)
turtle.right(90)
turtle.fd(20)
turtle.down()
turtle.color("White", "Dark Orange")
turtle.write("x", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-319.59, 120)
turtle.down()
but()
turtle.back(50)
turtle.right(90)
turtle.fd(20)
turtle.color("Black", "Dim Gray")
turtle.write("4", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-259.59, 120)
turtle.down()
but()
turtle.back(50)
turtle.right(90)
turtle.fd(20)
turtle.color("Black", "Dim Gray")
turtle.write("5", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-199.59, 120)
turtle.down()
but()
turtle.back(50)
turtle.right(90)
turtle.fd(20)
turtle.color("Black", "Dim Gray")
turtle.write("6", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-139.59, 120)
turtle.down()
turtle.color("Dim Gray", "Dark Orange")
turtle.begin_fill()
turtle.fd(59)
turtle.right(90)
turtle.fd(50)
turtle.right(90)
turtle.fd(59)
turtle.right(90)
turtle.fd(50)
turtle.end_fill()
turtle.up()
turtle.back(45)
turtle.right(90)
turtle.fd(24)
turtle.down()
turtle.color("White", "Dark Orange")
turtle.write("-", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-319.59, 70)
turtle.down()
but()
turtle.back(50)
turtle.right(90)
turtle.fd(20)
turtle.color("Black", "Dim Gray")
turtle.write("1", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-259.59, 70)
turtle.down()
but()
turtle.back(50)
turtle.right(90)
turtle.fd(20)
turtle.color("Black", "Dim Gray")
turtle.write("2", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-199.59, 70)
turtle.down()
but()
turtle.back(50)
turtle.right(90)
turtle.fd(20)
turtle.color("Black", "Dim Gray")
turtle.write("3", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-139.59, 70)
turtle.down()
turtle.color("Dim Gray", "Dark Orange")
turtle.begin_fill()
turtle.fd(59)
turtle.right(90)
turtle.fd(50)
turtle.right(90)
turtle.fd(59)
turtle.right(90)
turtle.fd(50)
turtle.end_fill()
turtle.up()
turtle.back(48)
turtle.right(90)
turtle.fd(20)
turtle.down()
turtle.color("White", "Dark Orange")
turtle.write("+", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-319.59, 20)
turtle.down()
turtle.color("Dim Gray", "Gray")
turtle.begin_fill()
turtle.fd(120)
turtle.right(90)
turtle.fd(50)
turtle.right(90)
turtle.fd(102)
for i in range(30):
    turtle.right(3)
    turtle.fd(1)
turtle.fd(30)
turtle.end_fill()
turtle.up()
turtle.back(50)
turtle.right(90)
turtle.fd(20)
turtle.down()
turtle.color("Black", "Dim Gray")
turtle.write("0", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-199.59, 20)
turtle.down()
but()
turtle.up()
turtle.back(40)
turtle.right(90)
turtle.fd(26)
turtle.down()
turtle.color("Black", "Dim Gray")
turtle.write(",", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-139.59, 20)
turtle.down()
turtle.color("Dim Gray", "Dark Orange")
turtle.begin_fill()
turtle.fd(59)
turtle.right(90)
turtle.fd(31)
for i in range(30):
    turtle.right(3)
    turtle.fd(1)
turtle.fd(40)
turtle.right(90)
turtle.fd(50)
turtle.end_fill()
turtle.up()
turtle.back(48)
turtle.right(90)
turtle.fd(20)
turtle.down()
turtle.color("White", "Dark Orange")
turtle.write("=", font=("AppleGothic", 32))
turtle.up()
turtle.setpos(-300, 220)
turtle.down()
turtle.color("White", "Gray")
while True:
    alex = turtle.getcanvas()
    alex.bind("<Button-1>", fly)
    turtle.listen()
    turtle.write(a, font = ("AppleGothic", 30))
turtle.done()
